### ISSUE TITLE
Zmiana hasła

### ISSUE THREAD

**Issue by ArturB** [ArturB/RSO#21]
Przy próbie zmiany hasła do konta, pojawia się komunikat "Błąd wystapił". Po polsku pisze się "Wystąpił błąd" no i na komunikacie nie ma żadnej informacji o przyczynie błędu. 

![obraz](https://user-images.githubusercontent.com/11396977/40786833-5cecdea6-64ec-11e8-8f46-a1570832b771.png)

**Comment by defacto2k15** [comment]
To jest niezaimplementowane w backendzie, komunikat zamieniony na polski

**Comment by ArturB** [comment]
Skoro jest niezaimplementowane w backendzie, to znaczy, że problem nie został rozwiązany, a zatem otwieram wątek ponownie.
