### ISSUE TITLE
Sortowanie alfabetyczne

### ISSUE THREAD

**Issue by ArturB** [ArturB/RSO#28]
Listy gmin, kandydatów i okręgów wyborczych powinny być moim zdaniem sortowane alfabetycznie
- w przypadku gmin i okręgów wyborczych po nazwie
- w przypadku kandydatów po nazwisku i potem imieniu
a nie po ID.

**Comment by ArturB** [comment]
Niestety problem nadal występuje, w przypadku partii, gmin, okręgów wyborczych, użytkowników i kandydatów. W ogóle wszystkich możliwych list. 
Przypominam:
 - partie, gminy i okręgi wyborcze sortujemy po nazwie
 - użytkowników po username
 - kandydatów po nazwisku i potem imieniu

![obraz](https://user-images.githubusercontent.com/11396977/40866463-123aeac0-65fe-11e8-9cb8-b487a79867ab.png)

![obraz](https://user-images.githubusercontent.com/11396977/40866485-218ae692-65fe-11e8-98a2-632b8418d449.png)

![obraz](https://user-images.githubusercontent.com/11396977/40866492-2bff883a-65fe-11e8-9e61-b670ebd0a4fa.png)

![obraz](https://user-images.githubusercontent.com/11396977/40866496-34e5efa2-65fe-11e8-9bc9-c1c583c18772.png)

![obraz](https://user-images.githubusercontent.com/11396977/40866507-3e482cf4-65fe-11e8-8b55-47c366ef2fa6.png)

**Comment by defacto2k15** [comment]
Jest sortowanie partii gmin i okręgów wyborczych. Kandydaci i użytkownicy powinni być sortowaniu u serwera
