### ISSUE TITLE
Edycja zabronionych encji przez administratora

### ISSUE THREAD

**Issue by ArturB** [ArturB/RSO#34]
Administrator ma możliwość utworzenia i edycji dowolnej encji, w tym np. votes_from_district, a to powinien móc zrobić tylko członek OKW.

**Comment by defacto2k15** [comment]
administrator już nie może

**Comment by ArturB** [comment]
Ja bym usunął jeszcze z admina pola "partia" i "kandydaci" bo to mogą edytować członkowie GKW no i zasadniczo to rejestracja kandydatów i partii jest zadaniem zdecentralizowanym, a nie problemem centralnym.
