### ISSUE TITLE
Wczytywanie listy kandydatów (potencjalnie każdej) [all]

### ISSUE THREAD

**Issue by ArturB** [ArturB/RSO#36]
Mając 1000 kandydatów, lista kandydatów ładuje się dość długo (kilka sekund) zrobiłbym progress bar albo wyświetlał kandydatów nie dopiero po załadowaniu wszystkich, ale po jednym (tzn załadowani kandydaci wyświetlają się na liście w czasie rzeczywistym podczas ładowania).

**Comment by defacto2k15** [comment]
Chodzi o oglądanie tego przed admina?

**Comment by ArturB** [comment]
No admin widzi chyba najwięcej tych kandydatów, więc w przypadku admina jest to najbardziej widoczne, ale dotyczy to potencjalnie każdej listy, jeśli tylko będzie odpowiednio długa.

**Comment by ArturB** [comment]
Problem zostanie rozwiązany przez [paginację list](https://github.com/ArturB/RSO/issues/55). Zamykam.
