### ISSUE TITLE
Votes_from_district.type [all]

### ISSUE THREAD

**Issue by ArturB** [ArturB/RSO#37]
Co oznacza pole "Type" przy wpisywaniu Votes_from_district?

**Comment by michaldzie** [comment]
Robiac baze danych domniemywałem ze chodzi o glosy wazne/nie wazne(i tu rodzaj nie ważności

**Comment by ArturB** [comment]
Skoro tak, to nie powinien to być text, tylko enum. I w bazie i JHipsterze (w JHipsterze powinno się wybierać to pole z combo-boxa, a nie wpisywać tekstem).
