### ISSUE TITLE
Wyniki wyborów - głosy nieważne - suwak [gkwmember]

### ISSUE THREAD

**Issue by ArturB** [ArturB/RSO#38]
W zakładce wyniki wyborów z poziomu gkwmember przy polu "głosy nieważne" jest suwak do zmiany liczby głosów nieważnych. Co prawda nie da się go kliknąć, ale nie powinno go tam być.

**Comment by defacto2k15** [comment]
U siebie nie widzę. Daj screena

**Comment by defacto2k15** [comment]
Dobra, już widzę. W ogóle suwaków nie powinno być moim zdaniem. Wywalam
