### ISSUE TITLE
Pole login przy tworzeniu nowego członka OKW

### ISSUE THREAD

**Issue by ArturB** [ArturB/RSO#46]
Podczas tworzenia nowego członka GKW widoczne jest pole Login, którego nie da się edytować. Oczywiście zgodnie z Programem funkcjonalno - użytkowym, login użytkownika generowany jest automatycznie na podstawie pozostałych danych, ale w takim wypadku tego pola nie powinno tam być. 

![obraz](https://user-images.githubusercontent.com/11396977/40866352-8725abc8-65fd-11e8-8409-0b67deafcb4b.png)

**Comment by defacto2k15** [comment]
już nie ma

**Comment by ArturB** [comment]
Co prawda problem nadal występuje, ale jak tak pomyślałem to nie jest to źle. Ponieważ login generowany jest automatycznie, a na maila wysyłamy tylko hasło, to nowy użytkownik nie wiedziałby jaka jest jego nazwa użytkownika. Także w sumie niech zostanie jak jest, tylko proszę Cię, żebyś pole Login przesunął na sam dół, jako końcową informację dla użytkownika, bo jak jest na samej górze to aż prosi się żeby coś tam wpisać.
