### ISSUE TITLE
Zmiana hasła bez zalogowania się

### ISSUE THREAD

**Issue by ArturB** [ArturB/RSO#54]
Na stronie startowej, przed zalogowaniem się, dostępny jest przycisk zmiany hasła. Co prawda po kliknięciu prosi o login i hasło, ale dopóki żaden użytkownik nie jest zalogowany, nie powinno go tam być. 

![obraz](https://user-images.githubusercontent.com/11396977/40873095-56347956-665a-11e8-8c1f-1eaeb73c7887.png)

**Comment by defacto2k15** [comment]
już nie może
