### ISSUE TITLE
Nie działa cofanie z widoku partii

### ISSUE THREAD

**Issue by ArturB** [ArturB/RSO#57]
Nie działa przycisk cofnij przy oglądaniu partii, ale tylko w specyficznej kombinacji ruchów.
Steps to replicate:
 - Zaloguj się jako gkwmember
 - wejdź w zakładkę kandydaci (mamy okres przedwyborczy)
 - wybierz przycisk oglądania jakiegoś kandydata (niebieskie oczko)
 - kliknij nazwę partii kandydata
 - zobaczysz opis partii, ale przycisk cofnij nie działa

To samo dotyczy przycisku cofnij podczas oglądania gminy, jeżeli kliknie się gminę z poziomu opisu kandydata, a także gdy wejdzie się najpierw w zakładkę Okręgi wyborcze a potem kliknie nazwę gminy. 

W pozostałych kombinacjach przycisk cofnij wydaje się działać.

**Comment by defacto2k15** [comment]
1. Czy chodzi o logowanie jako gkwmember? Okwmember nie ma dostępu do kandydatów,
2, Nie mogę odtworzyć błędu? Możesz u siebie to zrobić i wkleić log z konsoli JS?

**Comment by ArturB** [comment]
Tak pomyłka logujesz się jako gkwmember

**Comment by ArturB** [comment]
Ogólnie przycisk cofnij nie działa gdy wejdziesz w tryb oglądania jakiejś encji ale z poziomu oglądania innej encji, a nie bezpośrednio.

**Comment by defacto2k15** [comment]
już nie ma

**Comment by ArturB** [comment]
Problem został usunięty w przypadku partii, ale nadal występuje w przypadku gmin. 
"To samo dotyczy przycisku cofnij podczas oglądania gminy, jeżeli kliknie się gminę z poziomu opisu kandydata, a także gdy wejdzie się najpierw w zakładkę Okręgi wyborcze a potem kliknie nazwę gminy."
"Ogólnie przycisk cofnij nie działa gdy wejdziesz w tryb oglądania jakiejś encji ale z poziomu oglądania innej encji, a nie bezpośrednio."
